image: php:5.6
#image: ubuntu

#services:
#  - mysql:latest

#variables:
#  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#  MYSQL_DATABASE: $MYSQL_DB_NAME

#before_script:
#  - php -v
#  - curl --silent --show-error https://getcomposer.org/installer | php

#connect:
#  image: mysql
#  script:
#  - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=localhost "$MYSQL_DB_NAME"

cache:
  paths:
    - vendor/

stages:
  - test
#  - migrate # connect to remote database and make changes
  - deploy

test:
  before_script:
    - apt-get update
    - apt-get install -y git zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
#    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DB_NAME"
#    - php artisan migrate
  stage: test
  script:
    - ./vendor/bin/phpunit --configuration phpunit.xml

deploy:
  before_script:
    - apt-get update
    - apt-get install -y ftp
  stage: deploy
  script:
    - chmod +x CI-scripts/transfer.sh
    - ./CI-scripts/transfer.sh