image: php:5.6

cache:
  paths:
    - vendor/

stages:
  - test
#  - migrate # connect to remote database and make changes
  - deploy

test:
  before_script:
    - apt-get update
    - apt-get install -y git zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
    - chmod +x CI-scripts/*
    - ./CI-scripts/dropDatabase.sh
    - ./CI-scripts/createDB.sh
  stage: test
  script:
    - ./vendor/bin/phpunit --configuration phpunit.xml

deploy:
  before_script:
    - apt-get update
    - apt-get install -y ftp
  stage: deploy
  script:
    - chmod +x CI-scripts/transfer.sh
    - ./CI-scripts/transfer.sh